// 
// Generated from MapAction's Admin subdivision per country spreadsheet
// country_code: [adm0_name, adm1_name, adm2_name, adm3_name]
// 

const adminBoundaryNames = {
  "ABW": ["country","","",""],
  "AFG": ["country","province","district",""],
  "AGO": ["country","province","municipality","communes"],
  "AIA": ["country","","",""],
  "ALB": ["country","county","municipality","communes"],
  "AND": ["country","parish","",""],
  "ARE": ["country","Emirate","Municipal Region","Municipality"],
  "ARG": ["country","province/provincia","Partido",""],
  "ARM": ["country","Marz/province","unknown",""],
  "ASM": ["country","island/atoll","district","county"],
  "ATG": ["country","parish/dependency","",""],
  "AUS": ["country","territory/state","various",""],
  "AUT": ["country","region","county","unknown"],
  "AZE": ["country","İqtisadi Rayonu/region","/Sar/district/city",""],
  "BDI": ["country","province","commune",""],
  "BEL": ["country","region","province","county"],
  "BEN": ["country","department","commune","arrondissement"],
  "BES": ["country","island region","",""],
  "BFA": ["country","région","province","commune"],
  "BGD": ["country","division","district","upzilla"],
  "BGR": ["country","province","municipality",""],
  "BHR": ["country","Muhafazah/governate","",""],
  "BHS": ["country","district","town",""],
  "BIH": ["country","entity/condonimium","canton","unknown"],
  "BLM": ["country","","",""],
  "BLR": ["country","region/city","district",""],
  "BLZ": ["country","district","constituency",""],
  "BMU": ["country","parish","unknown",""],
  "BOL": ["country","Departamento/department","Provincia/province","Distrito/district"],
  "BRA": ["country","/state","/Municipality",""],
  "BRB": ["country","parish","",""],
  "BRN": ["country","districts/daerah","sub-district/mukims","village/kampung"],
  "BTN": ["country","district","municipality, sub-district, village block, village",""],
  "BWA": ["country","district/city/town","sub-district","unknown"],
  "CAF": ["country","prefecture","sub-prefecture","commune"],
  "CAN": ["country","province","Census Division","many"],
  "CCK": ["country","","",""],
  "CHE": ["country","canton","district","unknown"],
  "CHL": ["country","region","province","commune"],
  "CHN": ["country","provice","Dìjíshì/Prefecture City","Xiànjíshì/County City/various"],
  "CIV": ["country","district","region","department"],
  "CMR": ["country","region","department","commune"],
  "COD": ["country","kinshasa/province","city/teritory","communes/sector/chiefdom"],
  "COG": ["country","department","district",""],
  "COK": ["country","island council","",""],
  "COL": ["country","department","municipality",""],
  "COM": ["country","island","province","commune"],
  "CPV": ["country","municipality/concelhos","parish/freguesias",""],
  "CRI": ["country","province","canton","district"],
  "CUB": ["country","province/municipality","municipality",""],
  "CUW": ["country","","",""],
  "CXR": ["country","","",""],
  "CYM": ["country","district","",""],
  "CYP": ["country","control","district/base",""],
  "CZE": ["country","region","municipality",""],
  "DEU": ["country","city/territory state","district","unknown"],
  "DJI": ["country","region","district",""],
  "DMA": ["country","parish","",""],
  "DNK": ["country","region","municipality",""],
  "DOM": ["country","region","province","municipio"],
  "DZA": ["country","province/wilaya","district/daïra","municipality"],
  "ECU": ["country","province","cantoon","unknown"],
  "EGY": ["country","governorate","region","unknown"],
  "ERI": ["country","zoba","sub-zoba",""],
  "ESH": ["country","province","district",""],
  "ESP": ["country","autonomous communtiy/city","provinces","municipalities"],
  "EST": ["country","county","municipality","unknown"],
  "ETH": ["country","region","zone","woreda"],
  "FIN": ["country","region","sub-region","minicipality"],
  "FJI": ["country","district","province","tikina"],
  "FLK": ["country","","",""],
  "FRA": ["country","region","department","arrondissement"],
  "FRO": ["country","29 municipality","",""],
  "FSM": ["country","state","island",""],
  "GAB": ["country","province","department",""],
  "GBR": ["country","country","local authority",""],
  "GEO": ["country","Avtonomiuri Respublika/Autonomous Republic","Raioni/K'alak'i/District/city",""],
  "GGY": ["country","","",""],
  "GHA": ["country","region","district",""],
  "GIB": ["country","","",""],
  "GIN": ["country","region","prefecture","sub-prefecture"],
  "GLP": ["country","arrondissements","unknown",""],
  "GMB": ["country","region","district","ward"],
  "GNB": ["country","region/regiões/sector autónomo","sector/setores","sections/secções"],
  "GNQ": ["country","province","unknown",""],
  "GRC": ["country","Decentralized administrations","region",""],
  "GRD": ["country","parish","",""],
  "GRL": ["country","commune/national park","",""],
  "GTM": ["country","department","municipality",""],
  "GUF": ["country","arrondissement","commune","canton"],
  "GUM": ["country","municipality","",""],
  "GUY": ["country","region","council",""],
  "HND": ["country","departments","municipalities","aldeas"],
  "HRV": ["country","county/city","",""],
  "HTI": ["country","region","department","arrondissement"],
  "HUN": ["country","region/county/capital","district",""],
  "IDN": ["country","province/provinsi","city/district/regency/kota/kabupaten","district"],
  "IMN": ["country","sheeding","districts",""],
  "IND": ["country","Union Territory","District","Taluk"],
  "IOT": ["country","","",""],
  "IRL": ["country","county","",""],
  "IRN": ["country","province/ostan","county/Shahrestan",""],
  "IRQ": ["country","governorate","district","subdistrict"],
  "ISL": ["country","region","municipality",""],
  "ISR": ["country","Mehoz/district","unknown",""],
  "ITA": ["country","region","provice","unknown"],
  "JAM": ["country","parish","",""],
  "JEY": ["country","parish","unknown",""],
  "JOR": ["country","Muhafazah/province","Nahia/sub-province",""],
  "JPN": ["country","prefecture","city/town/village",""],
  "KAZ": ["country","region","district",""],
  "KEN": ["country","county","subcounty",""],
  "KGZ": ["country","province","district","community"],
  "KHM": ["country","province/capital","district/municipality/section","commune/quarter"],
  "KIR": ["country","island","unknown",""],
  "KNA": ["country","parish","",""],
  "KOR": ["country","division","district","unknown"],
  "KWT": ["country","Muhafazah/province","",""],
  "LAO": ["country","province","district",""],
  "LBN": ["country","Muhafazah/governate","/district","Municipality"],
  "LBR": ["country","county","district",""],
  "LBY": ["country","province","mintiqua","neighbourhood/baladiya"],
  "LCA": ["country","district","constituency",""],
  "LIE": ["country","district","municipality",""],
  "LKA": ["country","province","district","divsional secratairiats"],
  "LSO": ["country","district","constituency","community council"],
  "LTU": ["country","county","district","unknown"],
  "LUX": ["country","canton","comune",""],
  "LVA": ["country","municipality/city","parish",""],
  "MAF": ["country","","",""],
  "MAR": ["country","region","province","district"],
  "MCO": ["country","ward/quartier","",""],
  "MDA": ["country","district/municipality/autonomous entity","unknown",""],
  "MDG": ["country","region","district","commune"],
  "MDV": ["country","atoll/city","unknown",""],
  "MEX": ["country","/state","/Municipality",""],
  "MHL": ["country","municipality","district/village",""],
  "MKD": ["country","region","municipality",""],
  "MLI": ["country","region/district","cercles","commune"],
  "MLT": ["country","region","council",""],
  "MMR": ["country","subdivision","khayaing","mrui"],
  "MNE": ["country","municipality","",""],
  "MNG": ["country","province","soum",""],
  "MNP": ["country","Municipality","",""],
  "MOZ": ["country","province","district","posto"],
  "MRT": ["country","region/wilayas","department/moughataa","commune"],
  "MSR": ["country","parish","",""],
  "MTQ": ["country","arrondissement","commune",""],
  "MUS": ["country","region/district/autoarea","",""],
  "MWI": ["country","region","district","trad authority"],
  "MYS": ["country","state/federal state","unknown",""],
  "MYT": ["country","Chef-lieu canton/Préfecture de région/Sous-préfecture/commune","",""],
  "NAM": ["country","region","constituency",""],
  "NCL": ["country","province","Commune",""],
  "NER": ["country","region/région","department","commune"],
  "NFK": ["country","","",""],
  "NGA": ["country","state","local gov area",""],
  "NIC": ["country","department/autonomous region","municipality",""],
  "NIU": ["country","","",""],
  "NLD": ["country","province","municipality",""],
  "NOR": ["country","county","municipality",""],
  "NPL": ["country","province","district","municipality"],
  "NRU": ["country","district","village",""],
  "NZL": ["country","region","county","locality"],
  "OMN": ["country","Mintaqah/region","Wilayat/province",""],
  "PAK": ["country","province","district","tehsil"],
  "PAN": ["country","province/indigenous territory","district/indigenous territory","municpiality"],
  "PCN": ["country","","",""],
  "PER": ["country","region/province","province","district"],
  "PHL": ["country","region","province","municipality"],
  "PLW": ["country","region","locality",""],
  "PNG": ["country","province","district","local gov area"],
  "POL": ["country","province","county","municipality"],
  "PRI": ["territory","municipality","neighbourhood",""],
  "PRK": ["country","province/special city","county,/city/special city",""],
  "PRT": ["country","district","civil parish",""],
  "PRY": ["country","Departamento/department","Distrito/district",""],
  "PSE": ["country","region","governorate",""],
  "PYF": ["country","island","",""],
  "QAT": ["country","Baladiyah/municipality","unknown","unknown"],
  "REU": ["country","Arrondissement","commune",""],
  "ROU": ["country","county","town/commune",""],
  "RUS": ["country","Respublika/Republic/KrayTerritory","Raion/Gorsovet/Gorod/District/City",""],
  "RWA": ["country","province/city","district","sector"],
  "SAU": ["country","Minṭaqah/province","Muhafazah/governate",""],
  "SDN": ["country","state","district",""],
  "SEN": ["country","region","department","arrondissement"],
  "SGP": ["country","macrohood","neighbourhood",""],
  "SGS": ["country","","",""],
  "SHN": ["country","admin area/dependency","",""],
  "SJM": ["country","","",""],
  "SLB": ["country","province/territory","constituency","unknown"],
  "SLE": ["country","province","district","chiefdom"],
  "SLV": ["country","departamento","municipio","distrito"],
  "SMR": ["country","castelli/castle","",""],
  "SOM": ["country","region","district","unknown"],
  "SPM": ["country","commune","",""],
  "SRB": ["country","district","unknown",""],
  "SSD": ["country","state/admin area","county","unknown"],
  "STP": ["country","province","district",""],
  "SUR": ["country","district","resort",""],
  "SVK": ["country","region","district",""],
  "SVN": ["country","statistical regions","unknown",""],
  "SWE": ["country","country","municipality",""],
  "SWZ": ["country","region","inkhundla",""],
  "SXM": ["country","unknown","",""],
  "SYC": ["country","island","region","district"],
  "SYR": ["country","Muḥāfaẓah/governate","/district",""],
  "TCA": ["country","district","unknown",""],
  "TCD": ["country","province","department","sub-prefecture"],
  "TGO": ["country","region","perfecture","commune"],
  "THA": ["country","changwat","amphoe","tambon"],
  "TJK": ["country","region","district",""],
  "TKL": ["country","atoll","",""],
  "TKM": ["country","Welayat/province","Etrap/Şäher/Uly etrap/district/city/borough",""],
  "TLS": ["country","municipality","administrative post","village/sucos"],
  "TON": ["country","division","district","village"],
  "TTO": ["country","region/borough/city/ward","",""],
  "TUN": ["country","wilayah/governate/province","mutamadiyat/delegation","baladiyah/municipality"],
  "TUR": ["country","province","district","unknown"],
  "TUV": ["country","district","unknown","unknown"],
  "TWN": ["country","division (inc municipality, city, county)","township","village"],
  "TZA": ["country","region","district","ward"],
  "UGA": ["country","region","district","county"],
  "UKR": ["country","region/oblast/city","district/raion","hromadas"],
  "UMI": ["country","island","",""],
  "URY": ["country","Departamento/department","Municipio/Municipiality",""],
  "USA": ["country","state","county",""],
  "UZB": ["country","province","district",""],
  "VAT": ["country","","",""],
  "VCT": ["country","","parish",""],
  "VEN": ["country","state/federal dependency","municipality","unknown"],
  "VGB": ["country","district","",""],
  "VIR": ["country","province","municipality",""],
  "VNM": ["country","province","district","commune"],
  "VUT": ["country","province","municipality",""],
  "WLF": ["country","kingdom","district",""],
  "WSM": ["country","district","village",""],
  "XKX": ["country","district","municipality",""],
  "YEM": ["country","governorate","district","subdistrict"],
  "ZAF": ["country","province","district","local municipality"],
  "ZMB": ["country","province","district",""],
  "ZWE": ["country","province","district","ward"]
}

export default adminBoundaryNames
